'use client'

const DashboardPage = () => {
    console.log('Dashboard')
    return (
        <div>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
            <h1>Dashboard</h1>
        </div>
    )
}

export default DashboardPage;
